" Vimrc File

set nocompatible
filetype off

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle
Plugin 'VundleVim/Vundle.vim'

" Functionality Plugins
Plugin 'rust-lang/rust.vim'

"Plugin 'Valloric/YouCompleteMe'
"Plugin 'powerline/fonts'
"Plugin 'bling/vim-airline'
"Plugin 'vim-airline/vim-airline-themes'
Plugin 'scrooloose/nerdtree'
Plugin 'tpope/vim-fugitive' "Git branch tracking/Integrated Git commands
"Plugin 'edkolev/promptline.vim'

" Specific Language compatibility plugins
Plugin 'elixir-lang/vim-elixir'

" Static Analysis
Plugin 'wookiehangover/jshint.vim'

call vundle#end()
filetype plugin indent on

" Plugin Settings
set laststatus=2 "FIXME: What is this?
let g:airline_powerline_fonts = 1
let g:airline#extensions#tabline#enabled = 1
let g:airline#extensions#tabline#fnamemod = ':t'

" Basic config settings
set number
syntax on
set background=dark
colorscheme solarized

set expandtab
set tabstop=4
set shiftwidth=4
set softtabstop=4 "makes backspace feel like its a real tab

"KeyBindings
nnoremap <C-h> :tabprevious<CR>
nnoremap <C-l> :tabnext<CR>

" Source other config files
"so ~/.scvimrc " SuperCollider

" Fix for rust-lang plugin
autocmd BufNewFile,BufRead *.rs set filetype=rust

"========Experimental==========="

"Automatically create/load view files that save code folds between uses.
"http://vim.wikia.com/wiki/VimTip991
autocmd BufWinLeave *.* mkview
autocmd BufWinEnter *.* silent loadview
